[package]
name = "hacspec"
version = "0.1.1"
authors = ["Franziskus Kiefer <franziskuskiefer@gmail.com>"]
edition = "2018"
description = "A set of tools to write succinct crypto specs."
license = "Apache-2.0"

[lib]
path = "src/hacspec.rs"

[dependencies]
rand = "0.6" # ok?

[dev-dependencies]
wrapping_arithmetic = "0.1"
num = "0.2"
paste = "0.1"
uint = { git = "https://github.com/franziskuskiefer/rust-uint-n" }
# uint = { path = "../uint_n" }
