[package]
name = "hacspec"
version = "0.1.1"
authors = ["Franziskus Kiefer <franziskuskiefer@gmail.com>"]
description = "Nothing here yet"
license = "Apache-2.0"

[dependencies]
rand = "0.6" # ok?
abstract_integers = "0.1"

[patch.crates-io]
abstract_integers = { path = "../rust-abstract-integers" }
