name: Build & Test

on: [push, pull_request, release]

jobs:
  build:

    runs-on: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
