name: github pages

on:
  push:
    branches:
      - franziskus-doc

jobs:
  rustdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
      - uses: actions/checkout@master
      - name: Build docs
        run: |
          cargo doc --all-features
          touch target/doc/.nojekyll
          cat > target/doc/index.html <<EOF
          <!doctype html>
          <html><head>
            <meta http-equiv="refresh" content="0; URL='hacspec/index.html'" />
          </head></html>
          EOF
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@master
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: target/doc
